// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Thumbnail struct {
	VideoID string `json:"videoId"`
	URL     string `json:"url"`
}

type Video struct {
	ID        string     `json:"id"`
	Name      string     `json:"name"`
	URL       string     `json:"url"`
	Thumbnail *Thumbnail `json:"thumbnail"`
}

type VideoFilter struct {
	Actresses []*string `json:"actresses"`
}
